
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS"
export const SEARCH_DATA_FAIL = "SEARCH_DATA_FAIL"
export const SEARCH_DATA__DETAIL_SUCCESS = "SEARCH_DATA__DETAIL_SUCCESS"
export const SEARCH_DATA__DETAIL_FAIL = "SEARCH_DATA__DETAIL_FAIL"

export const SEARCH_KEY_SUCCESS = "SEARCH_KEY_SUCCESS"
export const SEARCH_KEY_FAIL = "SEARCH_KEY_FAIL"

