# Generated by Django 3.2.11 on 2022-02-13 21:05

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_displayed', models.BooleanField(default=True)),
                ('updated_by', models.CharField(default='System', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Unknown', max_length=280, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='System', max_length=200, null=True)),
                ('file', models.FileField(blank=True, default='null', null=True, upload_to=personal.models.upload_to)),
                ('is_displayed', models.BooleanField(default=True)),
                ('updated_by', models.CharField(default='System', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Unknown', max_length=280, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='System', max_length=200, null=True)),
                ('summary', models.CharField(default='System', max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('updated_by', models.CharField(default='System', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(default='Unknown', max_length=280, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='null', null=True, upload_to=personal.models.upload_to_project)),
            ],
        ),
    ]
