# Generated by Django 3.2.12 on 2022-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(default='null', max_length=200, null=True)),
                ('arrival', models.CharField(default='null', max_length=200, null=True)),
                ('departure_date', models.DateTimeField(auto_now=True, null=True)),
                ('arrival_date', models.DateTimeField(auto_now=True, null=True)),
                ('train_number', models.CharField(default='null', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(default='null', max_length=200, null=True)),
                ('capacity', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
