# Generated by Django 3.2.12 on 2022-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='arrival_date',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='departure_date',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
    ]
